### ISSUE TITLE
Make fails in test coverage

### ISSUE THREAD

**Issue by realamirhe** [zarbchain/zarb-go#297]
## Description

> Following the main instruction of zarb go, I got the following error, cause the `make` failed.
```bash
bash: zarb-daemon: command not found
```

### Expected Behavior

> It simply work, or update readme to fix the issue

### Extra

```bash
go test ./... -covermode=atomic
ok      github.com/zarbchain/zarb-go/account    0.110s  coverage: 93.1% of statements
ok      github.com/zarbchain/zarb-go/block      2.302s  coverage: 96.4% of statements
?       github.com/zarbchain/zarb-go/cmd        [no test files]
?       github.com/zarbchain/zarb-go/cmd/daemon [no test files]
?       github.com/zarbchain/zarb-go/cmd/wallet [no test files]
ok      github.com/zarbchain/zarb-go/committee  0.125s  coverage: 100.0% of statements
ok      github.com/zarbchain/zarb-go/config     0.071s  coverage: 72.5% of statements
ok      github.com/zarbchain/zarb-go/consensus  9.131s  coverage: 82.5% of statements
ok      github.com/zarbchain/zarb-go/consensus/log      0.096s  coverage: 90.4% of statements
ok      github.com/zarbchain/zarb-go/consensus/proposal 0.124s  coverage: 81.6% of statements
ok      github.com/zarbchain/zarb-go/consensus/vote     0.076s  coverage: 78.9% of statements
ok      github.com/zarbchain/zarb-go/consensus/voteset  0.190s  coverage: 94.6% of statements
ok      github.com/zarbchain/zarb-go/crypto     0.020s  coverage: 80.7% of statements
ok      github.com/zarbchain/zarb-go/crypto/bls 0.273s  coverage: 95.4% of statements
ok      github.com/zarbchain/zarb-go/crypto/hash        0.081s  coverage: 91.3% of statements
ok      github.com/zarbchain/zarb-go/encoding   0.077s  coverage: 98.3% of statements
ok      github.com/zarbchain/zarb-go/errors     0.067s  coverage: 88.2% of statements
ok      github.com/zarbchain/zarb-go/execution  0.280s  coverage: 95.1% of statements
ok      github.com/zarbchain/zarb-go/execution/executor 0.982s  coverage: 100.0% of statements
ok      github.com/zarbchain/zarb-go/genesis    0.090s  coverage: 89.4% of statements
ok      github.com/zarbchain/zarb-go/libs/bech32m       0.037s  coverage: 92.0% of statements
ok      github.com/zarbchain/zarb-go/libs/linkedmap     0.013s  coverage: 100.0% of statements
ok      github.com/zarbchain/zarb-go/libs/merkle        0.160s  coverage: 91.5% of statements
ok      github.com/zarbchain/zarb-go/libs/orderedmap    0.087s  coverage: 71.4% of statements
ok      github.com/zarbchain/zarb-go/logger     0.084s  coverage: 89.1% of statements
DEBU[0000] check connectivity                            _network="{0}" peers=0
DEBU[0000] peer count is less than minimum threshold     _network="{0}" count=0 threshold=4
DEBU[0000] peer store info                               _network="{0}" peers="[12D3KooWSZ3Yx1wJ2dGWQdxDW7MVVKcsuHwh7HZMvK9fx4fVa7mq]"
DEBU[0000] network setup                                 _network="{0}" address="[/ip4/0.0.0.0/tcp/19867]" id=12D3KooWSZ3Yx1wJ2dGWQdxDW7MVVKcsuHwh7HZMvK9fx4fVa7mq
2022/04/08 06:59:03 [zeroconf] no suitable IPv4 interface: udp4: failed to join any of these interfaces: []
2022/04/08 06:59:03 [zeroconf] no suitable IPv6 interface: udp6: failed to join any of these interfaces: []
--- FAIL: TestPubSub (0.02s)
    network_test.go:37: 
                Error Trace:    network_test.go:37
                                                        gossip_test.go:12
                Error:          Received unexpected error:
                                network error: no supported interface
                Test:           TestPubSub
DEBU[0000] check connectivity                            _network="{0}" peers=0
DEBU[0000] peer count is less than minimum threshold     _network="{0}" count=0 threshold=4
DEBU[0000] peer store info                               _network="{0}" peers="[12D3KooWF62F2n8uKhoTVrCQXsdVz864HTBr3SEhPKZWmxd8PQoF]"
DEBU[0000] network setup                                 _network="{0}" address="[/ip4/0.0.0.0/tcp/12202]" id=12D3KooWF62F2n8uKhoTVrCQXsdVz864HTBr3SEhPKZWmxd8PQoF
2022/04/08 06:59:03 [zeroconf] no suitable IPv4 interface: udp4: failed to join any of these interfaces: []
2022/04/08 06:59:03 [zeroconf] no suitable IPv6 interface: udp6: failed to join any of these interfaces: []
--- FAIL: TestJoinTopic (0.06s)
    network_test.go:37: 
                Error Trace:    network_test.go:37
                                                        gossip_test.go:23
                Error:          Received unexpected error:
                                network error: no supported interface
                Test:           TestJoinTopic
DEBU[0000] check connectivity                            _network="{0}" peers=0
DEBU[0000] peer count is less than minimum threshold     _network="{0}" count=0 threshold=4
DEBU[0000] peer store info                               _network="{0}" peers="[12D3KooWArSYBqeuXPzPAFbV2pxRsEAwnxUb4qr3N4hvwvWavNds]"
DEBU[0000] network setup                                 _network="{0}" address="[/ip4/0.0.0.0/tcp/19076]" id=12D3KooWArSYBqeuXPzPAFbV2pxRsEAwnxUb4qr3N4hvwvWavNds
2022/04/08 06:59:03 [zeroconf] no suitable IPv4 interface: udp4: failed to join any of these interfaces: []
2022/04/08 06:59:03 [zeroconf] no suitable IPv6 interface: udp6: failed to join any of these interfaces: []
--- FAIL: TestInvalidTopic (0.01s)
    network_test.go:37: 
                Error Trace:    network_test.go:37
                                                        gossip_test.go:32
                Error:          Received unexpected error:
                                network error: no supported interface
                Test:           TestInvalidTopic
DEBU[0000] check connectivity                            _network="{0}" peers=0
DEBU[0000] peer count is less than minimum threshold     _network="{0}" count=0 threshold=4
DEBU[0000] peer store info                               _network="{0}" peers="[12D3KooWPzttfxC9nAsx2QHamyQkXD13qrRreAf1HfshoRf9BCrn]"
DEBU[0000] network setup                                 _network="{0}" address="[/ip4/0.0.0.0/tcp/10489]" id=12D3KooWPzttfxC9nAsx2QHamyQkXD13qrRreAf1HfshoRf9BCrn
2022/04/08 06:59:03 [zeroconf] no suitable IPv4 interface: udp4: failed to join any of these interfaces: []
2022/04/08 06:59:03 [zeroconf] no suitable IPv6 interface: udp6: failed to join any of these interfaces: []
--- FAIL: TestStoppingNetwork (0.01s)
    network_test.go:37: 
                Error Trace:    network_test.go:37
                                                        network_test.go:64
                Error:          Received unexpected error:
                                network error: no supported interface
                Test:           TestStoppingNetwork
DEBU[0000] check connectivity                            _network="{0}" peers=0
DEBU[0000] peer count is less than minimum threshold     _network="{0}" count=0 threshold=4
DEBU[0000] peer store info                               _network="{0}" peers="[12D3KooWNHvVspSiUqc2Ys3kS8RFVQLqMaKC1dcG9XBKKuudJRKV]"
DEBU[0000] network setup                                 _network="{0}" address="[/ip4/0.0.0.0/tcp/10169]" id=12D3KooWNHvVspSiUqc2Ys3kS8RFVQLqMaKC1dcG9XBKKuudJRKV
2022/04/08 06:59:03 [zeroconf] no suitable IPv4 interface: udp4: failed to join any of these interfaces: []
2022/04/08 06:59:03 [zeroconf] no suitable IPv6 interface: udp6: failed to join any of these interfaces: []
--- FAIL: TestDHT (0.01s)
    network_test.go:37: 
                Error Trace:    network_test.go:37
                                                        network_test.go:73
                Error:          Received unexpected error:
                                network error: no supported interface
                Test:           TestDHT
DEBU[0000] check connectivity                            _network="{0}" peers=0
DEBU[0000] peer count is less than minimum threshold     _network="{0}" count=0 threshold=4
DEBU[0000] peer store info                               _network="{0}" peers="[12D3KooWT3Rzh2NqyAdfyHSKzB7Y91C3959JcX9NUuqxobrNQoFC]"
DEBU[0000] network setup                                 _network="{0}" address="[/ip4/0.0.0.0/tcp/15331]" id=12D3KooWT3Rzh2NqyAdfyHSKzB7Y91C3959JcX9NUuqxobrNQoFC
2022/04/08 06:59:03 [zeroconf] no suitable IPv4 interface: udp4: failed to join any of these interfaces: []
2022/04/08 06:59:03 [zeroconf] no suitable IPv6 interface: udp6: failed to join any of these interfaces: []
--- FAIL: TestStream (0.07s)
    network_test.go:37: 
                Error Trace:    network_test.go:37
                                                        stream_test.go:12
                Error:          Received unexpected error:
                                network error: no supported interface
                Test:           TestStream
FAIL
coverage: 32.2% of statements
FAIL    github.com/zarbchain/zarb-go/network    0.506s
2022/04/08 06:59:11 [zeroconf] no suitable IPv4 interface: udp4: failed to join any of these interfaces: []
2022/04/08 06:59:11 [zeroconf] no suitable IPv6 interface: udp6: failed to join any of these interfaces: []
--- FAIL: TestRunningNode (0.02s)
    node_test.go:36: 
                Error Trace:    node_test.go:36
                Error:          Received unexpected error:
                                network error: no supported interface
                Test:           TestRunningNode
FAIL
coverage: 41.5% of statements
FAIL    github.com/zarbchain/zarb-go/node       0.092s
?       github.com/zarbchain/zarb-go/param      [no test files]
ok      github.com/zarbchain/zarb-go/sandbox    12.969s coverage: 61.6% of statements
ok      github.com/zarbchain/zarb-go/sortition  4.831s  coverage: 98.6% of statements
ok      github.com/zarbchain/zarb-go/state      3.080s  coverage: 72.1% of statements
ok      github.com/zarbchain/zarb-go/state/lastinfo     0.111s  coverage: 97.2% of statements
ok      github.com/zarbchain/zarb-go/store      5.822s  coverage: 69.4% of statements
ok      github.com/zarbchain/zarb-go/sync       11.751s coverage: 88.6% of statements
ok      github.com/zarbchain/zarb-go/sync/bundle        0.900s  coverage: 86.1% of statements
ok      github.com/zarbchain/zarb-go/sync/bundle/message        0.701s  coverage: 74.1% of statements
ok      github.com/zarbchain/zarb-go/sync/cache 0.781s  coverage: 97.9% of statements
ok      github.com/zarbchain/zarb-go/sync/firewall      0.829s  coverage: 96.6% of statements
?       github.com/zarbchain/zarb-go/sync/peerset       [no test files]
Node 1 address: zc1p7qa6uhzgg44mzl8h87gz7sc8m6e0u4v95ar37f
Node 2 address: zc1puqcmm6pdzyj3344qqvxkmavzdr6pzck5dde7pc
Node 3 address: zc1pu9uqprskf9xv0674wx55audegcpa322ru9dy8k
Node 4 address: zc1pfes8sars9pxfqp7ddmfkf5le2xagm6erqz7krc
Node 5 address: zc1pfycpsx5hgwnkq5g0pj74evln5qwsuq5qgnyguu
Node 6 address: zc1ppzstzzfrlx4hqc6ej46hkgzle8de2puwyfm7p6
Node 7 address: zc1pjd4n7y3j9v0w2g382j52ysf678rz4p9zucxesw
Node 8 address: zc1pwgz4767nphpp6sjzzn2nv3xul8tphezcyg2d9y
ERRO[0000] error trying to connect to bootstrap node     _network="{0}" err="dial to self attempted" info="{12D3KooWCKKGMMGDhqRUZh6MnH2to6XUN9N2YPof4LrNNMe5Mbek: [/ip4/127.0.0.1/tcp/32125]}"
2022/04/08 06:59:11 [zeroconf] no suitable IPv4 interface: udp4: failed to join any of these interfaces: []
2022/04/08 06:59:11 [zeroconf] no suitable IPv6 interface: udp6: failed to join any of these interfaces: []
panic: Error on starting the node: network error: no supported interface

goroutine 1 [running]:
github.com/zarbchain/zarb-go/tests.TestMain(0x1821e9e8c8e6a)
        /workspace/zarb-go/tests/main_test.go:117 +0x1619
main.main()
        _testmain.go:93 +0x20f
FAIL    github.com/zarbchain/zarb-go/tests      0.077s
ok      github.com/zarbchain/zarb-go/tx 0.502s  coverage: 97.7% of statements
ok      github.com/zarbchain/zarb-go/tx/payload 0.077s  coverage: 22.0% of statements
ok      github.com/zarbchain/zarb-go/txpool     0.803s  coverage: 78.0% of statements
ok      github.com/zarbchain/zarb-go/util       0.104s  coverage: 82.9% of statements
ok      github.com/zarbchain/zarb-go/validator  0.126s  coverage: 93.6% of statements
?       github.com/zarbchain/zarb-go/version    [no test files]
ok      github.com/zarbchain/zarb-go/wallet     0.250s  coverage: 60.2% of statements
?       github.com/zarbchain/zarb-go/www/capnp  [no test files]
ok      github.com/zarbchain/zarb-go/www/grpc   0.159s  coverage: 59.2% of statements
?       github.com/zarbchain/zarb-go/www/grpc/proto     [no test files]
?       github.com/zarbchain/zarb-go/www/grpc/statik    [no test files]
ok      github.com/zarbchain/zarb-go/www/http   0.162s  coverage: 85.8% of statements
FAIL
make: *** [Makefile:45: test] Error 1
```

## Useful links

https://github.com/grandcat/zeroconf/blob/a393c0e41e54a80550bcf023c6bc11e6d4fc51db/connection.go#L93

### Environment
- **go version go1.18 linux/amd64**

**Comment by jwmdev** [comment]
@realamirhe 
Is this still an issue after upgrade of Zarb to go v1.19?

**Comment by b00f** [comment]
@jwmdev  It is fixed. I close it now.
